# Generated by Django 5.1.1 on 2024-09-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactname',
            unique_together={('user', 'global_phone_number')},
        ),
    ]
